name: Demo Workflow
on:
  push:
    branches:
    - main
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - run: echo "practice actions" > prac.txt
    - uses: actions/upload-artifact@v4
      with:
        name: prac-artifact
        path: ./prac.txt
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/download-artifact@v4
      with: 
        name: prac-artifact
    - run: cat prac.txt
