name: Demo Workflow
on:
  push:
    branches:
    - main
env:
  AWS_DEFAULT_REGION: ap-northeast-2
  ECR_REPOSITORY_NAME: 038462773075.dkr.ecr.ap-northeast-2.amazonaws.com/github-action

jobs:
  push:
    runs-on: [demo-runner]
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
    - uses: aws-actions/amazon-ecr-login@v2
    - uses: docker/build-push-action@v4
      with: 
        context: .
        push: true
        tags: ${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}
      
