name: Demo Workflow
on:
  push:
    branches:
    - main
env:
  GLOBAL_ENV: "global env"
jobs:
  job1:
    env:
      JOB_ENV: "job env"
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - env:
        STEP_ENV: "step env"
      run: |
        echo "actions github"
        echo "${{ toJSON(github) }}"
      

