name: Demo Workflow
on:
  push:
    branches:
    - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: print hello
      run: echo "hello"
    
# env:
#   AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
#   ECR_REPOSITORY_NAME: ${{ vars.ECR_REPOSITORY_NAME }}

# jobs:
#   push:
#     runs-on: [demo-runner]
#     steps:
#     - uses: actions/checkout@v4
#     - uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-region: ${{ env.AWS_DEFAULT_REGION }}
#     - uses: aws-actions/amazon-ecr-login@v2
#     - uses: docker/build-push-action@v6
#       with: 
#         context: .
#         push: true
#         tags: ${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}
      
